{% set name = "napari-psf-simulator" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-psf-simulator-{{ version }}.tar.gz
  sha256: 3d57b56a4731771dc45144850f55c76dfc9a7434aaf69520433245fd5dfc6da1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pycustomfocus >=3.3.6
    - python >={{ python_min }},<3.11
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_psf_simulator
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-psf-simulator
  summary: A plugin for simulations of the Point Spread Function, with aberrations
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/andreabassi78/napari-psf-simulator

extra:
  recipe-maintainers:
    - andreabassi78
    - goanpeca
    - jaimergp
